config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "about", to: "about#index"

  #Sign_up
  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  #Sign_in 
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  
  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
  
end

app/models/user.rb
class User < ApplicationRecord
  #?What we created
  #email: string
  #password_digest: string
  #
  #password: string
  #password_confirmation:string virtual

  #This is for have the password and password confirmation
  has_secure_password
  #Validations
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #Before to run the app, run:
  before_action :set_current_user

  def set_current_user 
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    #We save the informaton with user_params
    @user = User.new(user_params)
    if @user.save
      #Save the session of the user
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
      flash[:alert] = "Error al registrar el usuario"
      render :new
    end
  end

  private 

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in succesfully"
    else
      flash[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/about/index.html.erb
<h1>About page</h1>

app/views/home/index.html.erb
<div class="d-flex align-items-center justify-content-center flex-column">
  <h1>Welcome to Scheduled Tweets</h1>

  <div class="container">
    <% if Current.user %>
     <p>Logged in as: <strong><%= Current.user.email %></strong></p> 
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= render partial: 'shared/navbar' %>
    </div>
    
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "App example", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"%>
        </li>
      </ul>
    </div>
    
    <div class="flex">
      <% if !session[:user_id] %>
      <% if request.path != sign_up_path && request.path != sign_in_path  %>
        <%= link_to "Sign in", sign_in_path, class: "btn btn-primary" %>
        <%= link_to "Sign up", sign_up_path, class: "btn btn-dark" %>
      <% elsif request.path == sign_up_path %>
        <%= link_to "Sign in", sign_in_path, class: "btn btn-primary" %>
      <% elsif request.path == sign_in_path %>
        <%= link_to "Sign up", sign_up_path, class: "btn btn-dark" %>
      <% end %>
    <% end %>
    

    <% if session[:user_id] %>
      <%= button_to "logout", logout_path, method: :delete, class: "btn btn-danger"%>
    <% end %>
    </div>


  </div>
</nav>